// 환경변수 설정
// 배포 시 이 파일의 값을 실제 값으로 변경하세요
module.exports = {
    PORT: process.env.PORT || 8001,
    NODE_ENV: process.env.NODE_ENV || 'production',

    // Google Sheets 설정
    GOOGLE_SHEET_ID: process.env.GOOGLE_SHEET_ID || '1sUW4eRdXuTDyKY5VkNUfn9Ioam0ZQlSFNAaIIl-hujM',
    GOOGLE_SHEET_RANGE: process.env.GOOGLE_SHEET_RANGE || 'B73:F107',
    GOOGLE_SERVICE_ACCOUNT_EMAIL: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || 'cashflow-service@pkt-call.iam.gserviceaccount.com',
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY || `-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxJ6Z8hnaEpkzt
lIFCBWLtt5t3lqPDrWjn3EVjzvG/2gtu2LfGZX1x751bcUIuZIaUA7xJ/K7PlT2G
otZH3EGdMyM8RpCfgpZ3veOWkvNjJybHhqzrZ/xFlv4zR+h/imPjwbtoAvdB2X7i
QKc/2wYLYSBAWWWrAe2Myo1q2fSZfOF3dsCvauIiAG/jNqFZI7YW0qF/Mh5SFM5M
WKY+19ihWD9RW7yHk3c1xgCi35UBKYe0nJ2aCwJee/xM0IkSZHaoEd2pyLDfwMYm
ycOUxAlb6GyWIIvRkilYEKh4T9j4yeqsNslauOAvYrOPWCdKlgEBI76BSRbq4cDf
gwygcwfdAgMBAAECggEAC7hIzlzYQxGmwzebjtzrsjhUY7FRPOUgVz5+T1+7JJXD
QzO5LLnoIP0uLC+DplgQ2IKgFpujNlPJkeT8nMfDMNLXlj7rhcdONwvBSQ6IZYXg
jeX9/fDk1/cTnXGOExSlDnCcT6w/5AOvM5P9Zz8RLk2K+awwYAOCTgR/HejfbWFL
vn/qyInN4LNEha34YkLTp4RBeHAY1dyLkpkh6CEsavOYeeP9ifLWHYwCZZZH7AoP
+JxeE9s4jcR/FfA4CzPcPI78K0xdNrV7FEJbPi69hXw1KMHruwy42hdnrDpes8TN
E6rCZj65kPw4nNrchzI4aFwcmDg6njgyMptpl8ITIQKBgQDgDu/Q/zKeOE293HEr
QljHDSJINChycWGVUiIO4eMF569meXIredv2lAVi8NSoMZpVanzjpTxEzYElvckI
kx3QMZcDStMeqejdvT3naBm2csAN7rYY7q3KcOVt3BUgHIp152SgMzWarK55lHS/
Mqfw/kp+45GV7mVWI1DZpWQ/9QKBgQDKaPXdiNxs8GursSqK9Sn2R7YTsm6BHKDL
Zp4qfPQ9X38x6e7V7GmyZ2iQN7henHdwpAyiRBZqr/S0wlxj5PofG00W5SgznZ+X
YNxUH1J2ZzwrvUwSHPIxbfkxOV2aKxo6OjtlGsV45Z39fl+dbXEvkOZ1JoPeXoML
cqsmsHG/SQKBgCnqIWrTksCOf9yYtIMHMlxqVJN1Tmu6UisA5mYqU7HzGZjt9zGy
5jdGkYtkyiN8xAZemWZsrs2gNBy/WDBGdTlRTZLMGJqP5oQ0trPngYfkB5GTqnUX
kWNho0nd9gW/0RclZmmhqtF4pFsSLpTmAQzQRVdfcwi9RC/NA37ztcFRAoGBAILt
Udxy4uI0wfDVMMehvfroeAZVrNUnR3tKbZTeLr5kP0pyH2ORAO29pg1jfYb1fu0F
sIZltHpeRtOFxW14d7IXXs4ofNCmbMzmgp6HhDfCn1FLqSEuSBthH4ePq9RFfTmc
4T6NCp8hKAkI7aBPYp96AxhUSYhVaj7FdaAZEfrBAoGBAMty6nI9YoYCKAr+F0XG
PAK24vuJaJzwl8c2NVcJh6xOeVyrHS6P4Kek18QfTuTONbksNsCE9fkhGQ1C6tQa
uLvsxZU6Edtc+KeQsmW6Z1qSpiIsWQOnND6Hs8kaYYeWqMNijcbiibgiQUOdoEAL
cYkAu8CwfLcJOrx3GsGSyThe
-----END PRIVATE KEY-----`,
    GOOGLE_SERVICE_ACCOUNT_PROJECT_ID: process.env.GOOGLE_SERVICE_ACCOUNT_PROJECT_ID || 'pkt-call',

    // CORS
    CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:3000'
};
